name: CI
on:
  push:
    branches: [ master ]

jobs:
  FrontDeploy:
    name: FrontDeploy
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: setup Node
      uses: actions/setup-node@v1
      with: 
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: npm ci
    - name: Install Firebase
      run: npm install -g firebase-tools
    - name: Build
      run: npm run build
      
    - name: Restore Service Account
      working-directory: ./
      run: echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 --decode > service-account.json

    - name: deploy to Firebase Hosting
      run: firebase deploy
